In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
x,y = load_diabetes(return_X_y=True)

In [3]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

### using sklearn linear regression model

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)


In [5]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()


In [6]:
lr.fit (x_train,y_train)


LinearRegression()

In [71]:
lr.predict(x_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [12]:
x[0,:].reshape(1,10)
lr.predict(x)


array([209.72289501,  65.09056049, 179.16865788, 164.35025132,
       125.81936902, 107.70337073,  72.98315584, 117.65702433,
       158.25556257, 215.91874566,  95.35823382,  83.89513124,
       114.49551325, 169.82873534, 103.32081982, 176.92023466,
       217.31978192, 185.10384363, 144.73321989, 124.79033448,
       119.52440696,  84.09405192, 108.76342051, 253.48081489,
       162.48840259, 148.34935601,  96.85941882, 177.4392506 ,
       129.54414666, 196.03965176, 157.158263  ,  69.59671305,
       256.3310074 , 116.2371201 ,  74.64301228,  94.82613694,
       214.06781937, 159.60631862, 243.75835294, 138.88220139,
       152.7723085 ,  69.75842723, 145.57120278,  76.33579258,
       220.84543551, 127.36976245, 143.7842053 , 109.31936099,
        73.20971242, 189.67996707, 157.23922537, 172.01886812,
       131.71585918, 154.29258529, 136.84685487,  68.38335763,
       208.08242345,  79.60187569, 111.08217574, 139.46957799,
       113.43849679, 179.41109914,  58.44481069,  94.70

In [58]:
class MyMultipleLinearRegression:
    def __init__ (self):
        self.weights=None
        self.bias=None

    def fit (self, x_input,y_ouput):
        x_input= np.insert(x_input,0,1,axis=1)
        
        self.coef=np.dot(np.dot(np.linalg.inv(np.dot(x_input.T,x_input)),x_input.T),y_ouput)
        self.bias=self.coef[0]
        self.weights=self.coef[1:]

    def predict(self,x_train):
        return np.dot(np.insert(x_train,0,1,axis=1),self.coef)


In [59]:
lr1=MyMultipleLinearRegression()

In [60]:
from sklearn.datasets import load_diabetes
x,y = load_diabetes(return_X_y=True)


In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)


In [62]:
lr1.fit(x_train,y_train)

In [63]:
print(lr1.weights)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]


In [67]:
lr1.predict(x_test)


array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [53]:
print(lr1.bias)

151.8833100525417
